mysh: shell.c interpreter.c shellmemory.c scheduler.c
	gcc -c -D FRAMESIZE=$(framesize) -D VARMEMSIZE=$(varmemsize) shell.c interpreter.c shellmemory.c scheduler.c
	gcc -o mysh shell.o interpreter.o shellmemory.o scheduler.o

clean: 
	rm mysh; rm *.o


